version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: flaminDocker
      MYSQL_PASSWORD: flaminDocker
      MYSQL_DATABASE: image_flaminDocker
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)

    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
      
    networks:
      - backend


  app:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile-build-app
    environment:
      API_PORT: "8080"
      MYSQL_USER: flaminDocker
      MYSQL_PASSWORD: flaminDocker
      MYSQL_DATABASE: image_flaminDocker
      DB_HOST: tcp(db:3306)
    ports:
      - "8080:8080"
    volumes:
      - ./:/go:rw
    networks:
      - backend


  worker:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile-build-worker
    environment:
      API_PORT: "3000"
      MYSQL_USER: flaminDocker
      MYSQL_PASSWORD: flaminDocker
      MYSQL_DATABASE: image_flaminDocker
      DB_HOST: tcp(db:3306)
    ports:
      - "3000:3000"
    volumes:
      - ./:/go:rw
    networks:
      - backend


  redis-server: 
    image: redis:6.2

networks:
  backend:
    driver: "bridge"